### PR TITLE
[JA] translate Transaction-related words and sentences

### PR DESCRIPTION
**Pull request by develoQ**
- Transaction-related words and sentences
- Others that caught my eye at this time

### CODE REVIEW

**Comment by develoQ** [comment]
@N3TC4T 

I'd like to run Xumm locally (make or storybook) to check, but it does not work.
Is the documentation up to date?

**Comment by N3TC4T** [comment]
@develoQ if you follow the documentation you should be able to make it work for sure, can you make a issue with the description of your problem, so then I can look into it ?

**Comment by develoQ** [comment]
I have corrected the translation of the main sections (especially to the area visible in the read-only account) and the sections that I was noticing.

**Comment by N3TC4T** [comment]
Thanks @develoQ, really appreciate your effort, let me know when you are done with this pull request and i will merge it 🙏

**Comment by N3TC4T** [comment]
@develoQ Thank you very much for you effort and help, Please let me know when you are done with PR so I can merge it.

**Comment by develoQ** [comment]
I have done with work for this PR!

**Pull request merged**
